[tox]
envlist = py{310,311,312,313}, flake8, pylint

[testenv]
deps =
    pytest>=8.3,<9
commands =
    pytest {posargs}

[testenv:flake8]
skip_install = true
deps =
    flake8>=7.1,<8
commands =
    flake8 src/ --max-line-length 88
    flake8 tests/ --max-line-length 88

[flake8]
extend-ignore =
    # see https://github.com/psf/black/issues/315
    E203

[testenv:pylint]
deps =
    pylint>=3.3,<4
commands =
    # W0107: unnecessary pass statement. This is (mostly) a style issue: see https://github.com/pylint-dev/pylint/issues/2208
    # ignored-modules: avoid astroid recursion while inspecting scipy internals.
    pylint src/ --disable=C,R --disable=W0107 --ignored-modules=scipy,scipy.special --persistent=n

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313, flake8, pylint
